name: Publicar Imagen Docker

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-and-push-to-ghcr:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

    permissions:
      contents: read
      packages: write # Permiso para publicar en GHCR

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token automático de GitHub

      - name: Construir y publicar la imagen (CD)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ghcr.io/ingsis-second-chance/print-script-manager:${{ env.IMAGE_TAG }}
          file: ./Dockerfile

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push-to-ghcr

    env:
      SSH_KEY: ${{ github.ref_name == 'main' && secrets.SSH_KEY_PROD || secrets.SSH_KEY_DEV }}
      VM_IP: ${{ github.ref_name == 'main' && secrets.VM_PROD_IP || secrets.VM_DEV_IP }}
      DOCKER_COMPOSE_FILE: ${{ github.ref_name == 'main' && 'docker-compose.prod.yml' || 'docker-compose.dev.yml' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0 # Evita exponer la clave privada en los logs
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Deploy to Azure VM
        run: |
          ssh -v -o StrictHostKeyChecking=no ingsis@${{ env.VM_IP }} << 'ENDSSH'
          cd infra
          docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} down print-script-manager
          docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} pull print-script-manager
          docker compose -f ${{ env.DOCKER_COMPOSE_FILE }} up -d print-script-manager
          ENDSSH